// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurant.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO "restaurant" (name, description, address, category, city, district, logo_url, banner_url, phone_number, website_url, email, user_id)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateRestaurantParams struct {
	Name        string
	Description *string
	Address     *string
	Category    *string
	City        *string
	District    *string
	LogoUrl     *string
	BannerUrl   *string
	PhoneNumber *string
	WebsiteUrl  *string
	Email       *string
	UserID      uuid.UUID
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRestaurant,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.Category,
		arg.City,
		arg.District,
		arg.LogoUrl,
		arg.BannerUrl,
		arg.PhoneNumber,
		arg.WebsiteUrl,
		arg.Email,
		arg.UserID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getById = `-- name: GetById :one
SELECT id, name, description, address, category, city, district, logo_url, banner_url, phone_number, website_url, email, created_at, updated_at, user_id FROM "restaurant" WHERE id = $1
`

func (q *Queries) GetById(ctx context.Context, id int32) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Category,
		&i.City,
		&i.District,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.PhoneNumber,
		&i.WebsiteUrl,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getByName = `-- name: GetByName :one
SELECT id, name, description, address, category, city, district, logo_url, banner_url, phone_number, website_url, email, created_at, updated_at, user_id FROM "restaurant" WHERE name LIKE $1
`

func (q *Queries) GetByName(ctx context.Context, name string) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getByName, name)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Category,
		&i.City,
		&i.District,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.PhoneNumber,
		&i.WebsiteUrl,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
